KDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

.PHONY: all clean

all:
	@printf '%s\n' "Scaffold only. Add the PCI EDU IRQ driver logic and convert this file to standard kbuild."

clean:
	@:

